/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package VariaveiseTiposdeOperadores;

public class App {
    
    

    public static void main(String[] args) {
    
        //Sempre declaramos o tipo depois o nome começando com letra minuscula
        // posso definir um valor inicial colocando o valor após o "="
        int idade = 32;
        
    }
}
