/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package MeuPrimeiroProjeto;

public class App {
  //Barra, barra cria comentários de linha
    
  /* Forma de criar comentário de bloco */
  /** Forma para criar comentários de documentação do software*/

    public static void main(String[] args) {
        System.out.println ("Ola Mundo!");
    }
}
